[package]
name = "query"
version.workspace = true
edition.workspace = true

[[bin]]
name = "query"
path = "src/main.rs"

[dependencies]
anyhow = "1"
arrow = "53"
clap = { version = "4", features = ["derive"] }
datafusion = "43"
object_store = { version = "0.11", features = ["aws"] }
tokio = { version = "1", features = ["full"] }
url = "2"
